import { useEffect, useState } from 'react';
import Header from '../components/layout/Header';
import { getAdminOverview, updateAdminBusinessStatus, updateAdminProductStatus, type AdminBusiness, type AdminProduct, type AdminUser } from '../api/management.api';

export default function AdminOverview() {
  const [data, setData] = useState<{ users: AdminUser[]; businesses: AdminBusiness[]; products: AdminProduct[] } | null>(null); const [error, setError] = useState('');
  const refresh = () => getAdminOverview().then(setData).catch(() => setError('Unable to load admin data.'));
  useEffect(() => { void refresh(); }, []);
  return <div className="app dashboard-page"><Header /><main className="dashboard-shell"><div className="section-label">ADMINISTRATION</div><h1>Platform overview</h1>{error && <div className="error-message">{error}</div>}<div className="dashboard-stats"><div className="stat-card"><strong>{data?.users.length ?? 0}</strong><span>Users</span></div><div className="stat-card"><strong>{data?.businesses.length ?? 0}</strong><span>Businesses</span></div><div className="stat-card"><strong>{data?.products.length ?? 0}</strong><span>Products</span></div></div><section className="dashboard-panel"><h2>Businesses</h2>{data?.businesses.map((business) => <div className="dashboard-list-item" key={business.id}><div><strong>{business.name}</strong><span>{business.owner.email} · {business.status}</span></div><select value="" onChange={(event) => void updateAdminBusinessStatus(business.id, event.target.value).then(refresh).catch(() => setError('Unable to update business.'))}><option value="">Change status</option>{['ACTIVE', 'SUSPENDED', 'CLOSED'].map((status) => <option key={status} value={status}>{status}</option>)}</select></div>)}</section><section className="dashboard-panel"><h2>Products</h2>{data?.products.map((product) => <div className="dashboard-list-item" key={product.id}><div><strong>{product.name}</strong><span>{product.businessLocation.business.name} · {product.status}</span></div><select value="" onChange={(event) => void updateAdminProductStatus(product.id, event.target.value).then(refresh).catch(() => setError('Unable to update product.'))}><option value="">Change status</option>{['ACTIVE', 'INACTIVE', 'ARCHIVED'].map((status) => <option key={status} value={status}>{status}</option>)}</select></div>)}</section></main></div>;
}
