import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { registerBusiness } from '../api/auth.api';
import Header from '../components/layout/Header';

export default function BusinessRegister() {
  const navigate = useNavigate(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (form.get('password') !== form.get('confirmPassword')) { setError('Passwords must match.'); return; } setLoading(true); setError(''); try { await registerBusiness({ firstName: String(form.get('firstName')), lastName: String(form.get('lastName') || ''), email: String(form.get('email')), phone: String(form.get('phone') || ''), password: String(form.get('password')), businessName: String(form.get('businessName')), businessDescription: String(form.get('businessDescription') || ''), addressLine1: String(form.get('addressLine1')), city: String(form.get('city')), state: String(form.get('state') || ''), postalCode: String(form.get('postalCode') || ''), countryCode: String(form.get('countryCode')).toUpperCase(), latitude: Number(form.get('latitude')), longitude: Number(form.get('longitude')), termsAccepted: form.get('terms') === 'on', marketplaceRulesAccepted: form.get('rules') === 'on', privacyAccepted: form.get('privacy') === 'on' }); navigate('/business/login'); } catch { setError('Unable to register the business. Check the fields and agreements.'); } finally { setLoading(false); } };
  return <div className="auth-page app"><Header /><main className="auth-shell"><section className="auth-card"><div className="section-label">BUSINESS ACCESS</div><h1>Register Your Business</h1><form className="management-form" onSubmit={submit}><div className="auth-form-grid"><label>First name<input name="firstName" required /></label><label>Last name<input name="lastName" /></label></div><label>Email<input name="email" type="email" required /></label><label>Phone<input name="phone" /></label><label>Password<input name="password" type="password" minLength={8} required /></label><label>Confirm password<input name="confirmPassword" type="password" minLength={8} required /></label><label>Business name<input name="businessName" required /></label><label>Description<textarea name="businessDescription" /></label><label>Address line 1<input name="addressLine1" required /></label><div className="auth-form-grid"><label>City<input name="city" required /></label><label>State/province<input name="state" /></label></div><div className="auth-form-grid"><label>Country code<input name="countryCode" maxLength={2} required /></label><label>Postal code<input name="postalCode" /></label></div><div className="auth-form-grid"><label>Latitude<input name="latitude" type="number" step="any" required /></label><label>Longitude<input name="longitude" type="number" step="any" required /></label></div><label className="choice-row"><input name="terms" type="checkbox" required /> I accept the terms</label><label className="choice-row"><input name="rules" type="checkbox" required /> I accept marketplace rules</label><label className="choice-row"><input name="privacy" type="checkbox" required /> I accept the privacy policy</label>{error && <div className="error-message">{error}</div>}<button className="search-button auth-submit" disabled={loading}>{loading ? 'Submitting...' : 'Submit for approval'}</button></form><p className="auth-switch"><Link to="/business/login">Already an owner? Sign in</Link> · <Link to="/customer/register">Shopping instead? Create a customer account</Link></p></section></main></div>;
}
